### ISSUE TITLE
Instant crash when opening ImageActivity

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#17]
Stacktrace coming soon™....
Tested on Nexus 5 running 6.0.1

**Comment by CytoDev** [comment]
Hm... Never had this issue. Not on emulator nor real phone. Although I'm a few versions ahead... xD

**Comment by GijsTimmers** [comment]
Happens to me too on f7c28ea5b19adbaa43c7bf3b85d18fa485c44d74, on stock Kitkat.

**Comment by jariz** [comment]
Thanks @GijsTimmers. Knew I wasn't crazy :stuck_out_tongue: 
Stacktrace:
```
01-07 09:47:10.229 11185-11185/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: io.jari.dumpert, PID: 11185
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{io.jari.dumpert/io.jari.dumpert.activities.ImageActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:422)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                       at io.jari.dumpert.activities.ImageActivity.onCreate(ImageActivity.java:65)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by jariz** [comment]
Nvm, indeed fixed in @CytoDev's branch which was just merged now.

**Comment by GijsTimmers** [comment]
Still happens on my device.

[`adb logcat | grep 2180` output](http://paste.ubuntu.com/14428927/)

**Comment by jariz** [comment]
Lol you're right. it's happening again here as well.
It only happens when you're using a theme that isn't the default (green) it seems!

**Comment by CytoDev** [comment]
I might have...

**Comment by CytoDev** [comment]
Previous commit to themeFix branch should fix this issue, or at least stop from crashing. We can work from there.

**Comment by CytoDev** [comment]
![works-on-my-machine-starburst](https://cloud.githubusercontent.com/assets/5646869/12168649/f0788f00-b533-11e5-8008-b29c43ae1058.jpg)

**Comment by GijsTimmers** [comment]
![screenshot_2016-01-07-11-56-06](https://cloud.githubusercontent.com/assets/972314/12168964/eebde140-b535-11e5-9408-065b27218b0c.png)

**Comment by CytoDev** [comment]
I take it it is working then.
